import { CameraNode } from "./types";

export const DEFAULT_NODES: CameraNode[] = [
  { id: "cam-1", name: "Camera 01", x: 31, y: 9 },
  { id: "cam-2", name: "Camera 02", x: 40, y: 68 },
  { id: "cam-3", name: "Camera 03", x: 17, y: 76 },
  { id: "cam-4", name: "Camera 04", x: 94, y: 76 },
];

export const TOTAL_DURATION = 70; // 1:10 in seconds

export const CHOREOGRAPHED_EVENTS = [
  // Camera 1 (all faint — distant audio)
  { id: 'c1-01', nodeId: 'cam-1', label: 'Gunshots (Faint)', timestamp: 2, isGunfire: true },
  { id: 'c1-02', nodeId: 'cam-1', label: '"I hate this school!" (Faint)', timestamp: 5 },
  { id: 'c1-03', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 8 },
  { id: 'c1-04', nodeId: 'cam-1', label: 'Gunshots (Faint)', timestamp: 9, isGunfire: true },
  { id: 'c1-05', nodeId: 'cam-1', label: '"You\'re all gonna fucking pay!" (Faint)', timestamp: 12 },
  { id: 'c1-06', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 14 },
  { id: 'c1-07', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 15 },
  { id: 'c1-08', nodeId: 'cam-1', label: '"I\'ll kill you all!" (Faint)', timestamp: 17 },
  { id: 'c1-09', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 18 },
  { id: 'c1-10', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 18.5 },
  { id: 'c1-11', nodeId: 'cam-1', label: '"Get out! Hands up! Police!" (Faint)', timestamp: 28 },
  { id: 'c1-12', nodeId: 'cam-1', label: '"Police!" (Faint)', timestamp: 30 },
  { id: 'c1-13', nodeId: 'cam-1', label: '"Where is he, where is he?" (Faint)', timestamp: 31 },
  { id: 'c1-14', nodeId: 'cam-1', label: '"Put your hands up!" (Faint)', timestamp: 33 },
  { id: 'c1-15', nodeId: 'cam-1', label: '"Put your hands up! Where are you?" (Faint)', timestamp: 35 },
  { id: 'c1-16', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 37 },
  { id: 'c1-17', nodeId: 'cam-1', label: '"Backup!" (Faint)', timestamp: 38 },
  { id: 'c1-18', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 40 },
  { id: 'c1-19', nodeId: 'cam-1', label: '"Where is he?" (Faint)', timestamp: 41 },
  { id: 'c1-20', nodeId: 'cam-1', label: '"Where is he? Where?" (Faint)', timestamp: 42 },
  { id: 'c1-21', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 62 },

  // Camera 3
  { id: 'c3-01', nodeId: 'cam-3', label: 'Gunshots', timestamp: 2, isGunfire: true },
  { id: 'c3-02', nodeId: 'cam-3', label: '"I hate this school!"', timestamp: 5 },
  { id: 'c3-03', nodeId: 'cam-3', label: 'Gunshots', timestamp: 9, isGunfire: true },
  { id: 'c3-04', nodeId: 'cam-3', label: '"You\'re all gonna fucking pay!"', timestamp: 12 },
  { id: 'c3-05', nodeId: 'cam-3', label: '"I\'ll kill you all!"', timestamp: 17 },
  { id: 'c3-06', nodeId: 'cam-3', label: '"I see you in there!"', timestamp: 21 },
  { id: 'c3-07', nodeId: 'cam-3', label: '"I see you!"', timestamp: 24 },
  { id: 'c3-08', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 27, isGunfire: true },
  { id: 'c3-09', nodeId: 'cam-3', label: 'Yelling (Faint)', timestamp: 28 },
  { id: 'c3-10', nodeId: 'cam-3', label: '"Put your hands up, police!"', timestamp: 30 },
  { id: 'c3-11', nodeId: 'cam-3', label: '"Police! Where is he? Where is he?"', timestamp: 31 },
  { id: 'c3-12', nodeId: 'cam-3', label: '"Put your hands up!"', timestamp: 33 },
  { id: 'c3-13', nodeId: 'cam-3', label: '"Put your hands up! Where are you?"', timestamp: 35 },
  { id: 'c3-14', nodeId: 'cam-3', label: 'Running', timestamp: 37 },
  { id: 'c3-15', nodeId: 'cam-3', label: '"Backup!"', timestamp: 38 },
  { id: 'c3-16', nodeId: 'cam-3', label: 'Running', timestamp: 40 },
  { id: 'c3-17', nodeId: 'cam-3', label: '"Where is he?"', timestamp: 41 },
  { id: 'c3-18', nodeId: 'cam-3', label: '"Where is he? Where?" (Faint)', timestamp: 42 },
  { id: 'c3-19', nodeId: 'cam-3', label: 'Running (Faint)', timestamp: 48 },
  { id: 'c3-20', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 57, isGunfire: true },
  { id: 'c3-21', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 61, isGunfire: true },
  { id: 'c3-22', nodeId: 'cam-3', label: 'Screaming (Faint)', timestamp: 62 },
  { id: 'c3-23', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 64, isGunfire: true },
  { id: 'c3-24', nodeId: 'cam-3', label: 'Yelling (Faint)', timestamp: 65 },

  // Camera 4
  { id: 'c4-01', nodeId: 'cam-4', label: '"And then I told him, I was like, so surprised!"', timestamp: 1 },
  { id: 'c4-02', nodeId: 'cam-4', label: '"One sec, one sec"', timestamp: 4 },
  { id: 'c4-03', nodeId: 'cam-4', label: '"I hate this school!" (Faint)', timestamp: 5 },
  { id: 'c4-04', nodeId: 'cam-4', label: '"Oh my God. Is that…"', timestamp: 7 },
  { id: 'c4-05', nodeId: 'cam-4', label: 'Screaming', timestamp: 8 },
  { id: 'c4-06', nodeId: 'cam-4', label: '"I think that\'s gunshots!"', timestamp: 9 },
  { id: 'c4-07', nodeId: 'cam-4', label: 'Screaming', timestamp: 12 },
  { id: 'c4-08', nodeId: 'cam-4', label: '"You\'re all gonna fucking pay!" (Faint)', timestamp: 12.5 },
  { id: 'c4-09', nodeId: 'cam-4', label: 'Gunshots', timestamp: 15, isGunfire: true },
  { id: 'c4-10', nodeId: 'cam-4', label: '"I\'ll kill you all!" (Faint)', timestamp: 17 },
  { id: 'c4-11', nodeId: 'cam-4', label: '"I see you in there!" (Faint)', timestamp: 21 },
  { id: 'c4-12', nodeId: 'cam-4', label: '"I see you!" (Faint)', timestamp: 24 },
  { id: 'c4-13', nodeId: 'cam-4', label: 'Gunshots', timestamp: 27, isGunfire: true },
  { id: 'c4-14', nodeId: 'cam-4', label: 'Yelling', timestamp: 28 },
  { id: 'c4-15', nodeId: 'cam-4', label: '"Where is he, where is he?" (Faint)', timestamp: 31 },
  { id: 'c4-16', nodeId: 'cam-4', label: '"Put your hands up!" (Faint)', timestamp: 33 },
  { id: 'c4-17', nodeId: 'cam-4', label: '"Put your hands up! Where are you?"', timestamp: 35 },
  { id: 'c4-18', nodeId: 'cam-4', label: 'Running', timestamp: 37 },
  { id: 'c4-19', nodeId: 'cam-4', label: '"Backup!"', timestamp: 38 },
  { id: 'c4-20', nodeId: 'cam-4', label: 'Running', timestamp: 40 },
  { id: 'c4-21', nodeId: 'cam-4', label: '"Where is he?"', timestamp: 41 },
  { id: 'c4-22', nodeId: 'cam-4', label: '"Where is he? Where?"', timestamp: 42 },
  { id: 'c4-23', nodeId: 'cam-4', label: 'Running', timestamp: 48 },
  { id: 'c4-24', nodeId: 'cam-4', label: '"Standby, we\'re standing outside…"', timestamp: 53 },
  { id: 'c4-25', nodeId: 'cam-4', label: 'Gunshots', timestamp: 57, isGunfire: true },
  { id: 'c4-26', nodeId: 'cam-4', label: '"Hit!"', timestamp: 58 },
  { id: 'c4-27', nodeId: 'cam-4', label: '"Hit!"', timestamp: 59 },
  { id: 'c4-28', nodeId: 'cam-4', label: 'Gunshots', timestamp: 61, isGunfire: true },
  { id: 'c4-29', nodeId: 'cam-4', label: 'Screaming', timestamp: 62 },
  { id: 'c4-30', nodeId: 'cam-4', label: '"Standby, shots being fired"', timestamp: 63 },
  { id: 'c4-31', nodeId: 'cam-4', label: 'Gunshots', timestamp: 64, isGunfire: true },
  { id: 'c4-32', nodeId: 'cam-4', label: '"Grab the long gun, get in there!"', timestamp: 65 },
  { id: 'c4-33', nodeId: 'cam-4', label: '"Get the long gun!"', timestamp: 67 },
];
