import { CameraNode } from "./types";

export const DEFAULT_NODES: CameraNode[] = [
  { id: "cam-1", name: "Camera 01", x: 31, y: 9 },
  { id: "cam-2", name: "Camera 02", x: 40, y: 68 },
  { id: "cam-3", name: "Camera 03", x: 17, y: 76 },
  { id: "cam-4", name: "Camera 04", x: 85, y: 76 },
];

export const TOTAL_DURATION = 70; // 1:10 in seconds

export const CHOREOGRAPHED_EVENTS = [
  // Camera 1 (all faint — distant audio)
  { id: 'c1-01', nodeId: 'cam-1', label: 'Gunshots (Faint)', timestamp: 3, isGunfire: true },
  { id: 'c1-02', nodeId: 'cam-1', label: '"I hate this school!" (Faint)', timestamp: 6 },
  { id: 'c1-03', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 9 },
  { id: 'c1-04', nodeId: 'cam-1', label: 'Gunshots (Faint)', timestamp: 10, isGunfire: true },
  { id: 'c1-05', nodeId: 'cam-1', label: '"You\'re all gonna fucking pay!" (Faint)', timestamp: 13 },
  { id: 'c1-06', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 15 },
  { id: 'c1-07', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 16 },
  { id: 'c1-08', nodeId: 'cam-1', label: '"I\'ll kill you all!" (Faint)', timestamp: 18 },
  { id: 'c1-09', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 19 },
  { id: 'c1-10', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 19.5 },
  { id: 'c1-11', nodeId: 'cam-1', label: '"Get out! Hands up! Police!" (Faint)', timestamp: 29 },
  { id: 'c1-12', nodeId: 'cam-1', label: '"Police!" (Faint)', timestamp: 31 },
  { id: 'c1-13', nodeId: 'cam-1', label: '"Where is he, where is he?" (Faint)', timestamp: 32 },
  { id: 'c1-14', nodeId: 'cam-1', label: '"Put your hands up!" (Faint)', timestamp: 34 },
  { id: 'c1-15', nodeId: 'cam-1', label: '"Put your hands up! Where are you?" (Faint)', timestamp: 36 },
  { id: 'c1-16', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 38 },
  { id: 'c1-17', nodeId: 'cam-1', label: '"Backup!" (Faint)', timestamp: 39 },
  { id: 'c1-18', nodeId: 'cam-1', label: 'Running (Faint)', timestamp: 41 },
  { id: 'c1-19', nodeId: 'cam-1', label: '"Where is he?" (Faint)', timestamp: 42 },
  { id: 'c1-20', nodeId: 'cam-1', label: '"Where is he? Where?" (Faint)', timestamp: 43 },
  { id: 'c1-21', nodeId: 'cam-1', label: 'Screaming (Faint)', timestamp: 63 },

  // Camera 2
  { id: 'c2-01', nodeId: 'cam-2', label: 'Gunshots (Faint)', timestamp: 3, isGunfire: true },
  { id: 'c2-02', nodeId: 'cam-2', label: '"I hate this school!"', timestamp: 6 },
  { id: 'c2-03', nodeId: 'cam-2', label: 'Screaming (Faint)', timestamp: 9 },
  { id: 'c2-04', nodeId: 'cam-2', label: '"You\'re all gonna fucking pay!"', timestamp: 13 },
  { id: 'c2-04b', nodeId: 'cam-2', label: 'Gunshots (Faint)', timestamp: 10, isGunfire: true },
  { id: 'c2-05', nodeId: 'cam-2', label: 'Gunshots', timestamp: 16, isGunfire: true },
  { id: 'c2-06', nodeId: 'cam-2', label: '"I\'ll kill you all!"', timestamp: 18 },
  { id: 'c2-07', nodeId: 'cam-2', label: '"I see you in there!"', timestamp: 22 },
  { id: 'c2-08', nodeId: 'cam-2', label: '"I see you!"', timestamp: 25 },
  { id: 'c2-09', nodeId: 'cam-2', label: 'Gunshots', timestamp: 28, isGunfire: true },
  { id: 'c2-10', nodeId: 'cam-2', label: 'Yelling', timestamp: 29 },
  { id: 'c2-11', nodeId: 'cam-2', label: '"Put your hands up, police!"', timestamp: 31 },
  { id: 'c2-12', nodeId: 'cam-2', label: '"Police! Where is he? Where is he?"', timestamp: 32 },
  { id: 'c2-13', nodeId: 'cam-2', label: '"Put your hands up!"', timestamp: 34 },
  { id: 'c2-14', nodeId: 'cam-2', label: '"Put your hands up! Where are you?"', timestamp: 36 },
  { id: 'c2-15', nodeId: 'cam-2', label: 'Running', timestamp: 38 },
  { id: 'c2-16', nodeId: 'cam-2', label: '"Backup!"', timestamp: 39 },
  { id: 'c2-17', nodeId: 'cam-2', label: 'Running', timestamp: 41 },
  { id: 'c2-18', nodeId: 'cam-2', label: '"Where is he?"', timestamp: 42 },
  { id: 'c2-19', nodeId: 'cam-2', label: '"Where is he? Where?"', timestamp: 43 },
  { id: 'c2-20', nodeId: 'cam-2', label: 'Running', timestamp: 49 },
  { id: 'c2-21', nodeId: 'cam-2', label: 'Gunshots (Faint)', timestamp: 54, isGunfire: true },
  { id: 'c2-22', nodeId: 'cam-2', label: 'Gunshots (Faint)', timestamp: 62, isGunfire: true },
  { id: 'c2-23', nodeId: 'cam-2', label: 'Gunshots (Faint)', timestamp: 65, isGunfire: true },

  // Camera 3
  { id: 'c3-01', nodeId: 'cam-3', label: 'Gunshots', timestamp: 3, isGunfire: true },
  { id: 'c3-02', nodeId: 'cam-3', label: '"I hate this school!"', timestamp: 6 },
  { id: 'c3-03', nodeId: 'cam-3', label: 'Gunshots', timestamp: 10, isGunfire: true },
  { id: 'c3-04', nodeId: 'cam-3', label: '"You\'re all gonna fucking pay!"', timestamp: 13 },
  { id: 'c3-05', nodeId: 'cam-3', label: '"I\'ll kill you all!"', timestamp: 18 },
  { id: 'c3-06', nodeId: 'cam-3', label: '"I see you in there!"', timestamp: 22 },
  { id: 'c3-07', nodeId: 'cam-3', label: '"I see you!"', timestamp: 25 },
  { id: 'c3-08', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 28, isGunfire: true },
  { id: 'c3-09', nodeId: 'cam-3', label: 'Yelling (Faint)', timestamp: 29 },
  { id: 'c3-10', nodeId: 'cam-3', label: '"Put your hands up, police!"', timestamp: 31 },
  { id: 'c3-11', nodeId: 'cam-3', label: '"Police! Where is he? Where is he?"', timestamp: 32 },
  { id: 'c3-12', nodeId: 'cam-3', label: '"Put your hands up!"', timestamp: 34 },
  { id: 'c3-13', nodeId: 'cam-3', label: '"Put your hands up! Where are you?"', timestamp: 36 },
  { id: 'c3-14', nodeId: 'cam-3', label: 'Running', timestamp: 38 },
  { id: 'c3-15', nodeId: 'cam-3', label: '"Backup!"', timestamp: 39 },
  { id: 'c3-16', nodeId: 'cam-3', label: 'Running', timestamp: 41 },
  { id: 'c3-17', nodeId: 'cam-3', label: '"Where is he?"', timestamp: 42 },
  { id: 'c3-18', nodeId: 'cam-3', label: '"Where is he? Where?" (Faint)', timestamp: 43 },
  { id: 'c3-19', nodeId: 'cam-3', label: 'Running (Faint)', timestamp: 49 },
  { id: 'c3-20', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 58, isGunfire: true },
  { id: 'c3-21', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 62, isGunfire: true },
  { id: 'c3-22', nodeId: 'cam-3', label: 'Screaming (Faint)', timestamp: 63 },
  { id: 'c3-23', nodeId: 'cam-3', label: 'Gunshots (Faint)', timestamp: 65, isGunfire: true },
  { id: 'c3-24', nodeId: 'cam-3', label: 'Yelling (Faint)', timestamp: 66 },

  // Camera 4
  { id: 'c4-01', nodeId: 'cam-4', label: '"And then I told him, I was like, so surprised!"', timestamp: 2 },
  { id: 'c4-02', nodeId: 'cam-4', label: '"One sec, one sec"', timestamp: 5 },
  { id: 'c4-03', nodeId: 'cam-4', label: '"I hate this school!" (Faint)', timestamp: 6 },
  { id: 'c4-04', nodeId: 'cam-4', label: '"Oh my God. Is that…"', timestamp: 8 },
  { id: 'c4-05', nodeId: 'cam-4', label: 'Screaming', timestamp: 9 },
  { id: 'c4-06', nodeId: 'cam-4', label: '"I think that\'s gunshots!"', timestamp: 10 },
  { id: 'c4-07', nodeId: 'cam-4', label: 'Screaming', timestamp: 13 },
  { id: 'c4-08', nodeId: 'cam-4', label: '"You\'re all gonna fucking pay!" (Faint)', timestamp: 13.5 },
  { id: 'c4-09', nodeId: 'cam-4', label: 'Gunshots', timestamp: 16, isGunfire: true },
  { id: 'c4-10', nodeId: 'cam-4', label: '"I\'ll kill you all!" (Faint)', timestamp: 18 },
  { id: 'c4-11', nodeId: 'cam-4', label: '"I see you in there!" (Faint)', timestamp: 22 },
  { id: 'c4-12', nodeId: 'cam-4', label: '"I see you!" (Faint)', timestamp: 25 },
  { id: 'c4-13', nodeId: 'cam-4', label: 'Gunshots', timestamp: 28, isGunfire: true },
  { id: 'c4-14', nodeId: 'cam-4', label: 'Yelling', timestamp: 29 },
  { id: 'c4-15', nodeId: 'cam-4', label: '"Where is he, where is he?" (Faint)', timestamp: 32 },
  { id: 'c4-16', nodeId: 'cam-4', label: '"Put your hands up!" (Faint)', timestamp: 34 },
  { id: 'c4-17', nodeId: 'cam-4', label: '"Put your hands up! Where are you?"', timestamp: 36 },
  { id: 'c4-18', nodeId: 'cam-4', label: 'Running', timestamp: 38 },
  { id: 'c4-19', nodeId: 'cam-4', label: '"Backup!"', timestamp: 39 },
  { id: 'c4-20', nodeId: 'cam-4', label: 'Running', timestamp: 41 },
  { id: 'c4-21', nodeId: 'cam-4', label: '"Where is he?"', timestamp: 42 },
  { id: 'c4-22', nodeId: 'cam-4', label: '"Where is he? Where?"', timestamp: 43 },
  { id: 'c4-23', nodeId: 'cam-4', label: 'Running', timestamp: 49 },
  { id: 'c4-24', nodeId: 'cam-4', label: '"Standby, we\'re standing outside…"', timestamp: 54 },
  { id: 'c4-25', nodeId: 'cam-4', label: 'Gunshots', timestamp: 58, isGunfire: true },
  { id: 'c4-26', nodeId: 'cam-4', label: '"Hit!"', timestamp: 59 },
  { id: 'c4-27', nodeId: 'cam-4', label: '"Hit!"', timestamp: 60 },
  { id: 'c4-28', nodeId: 'cam-4', label: 'Gunshots', timestamp: 62, isGunfire: true },
  { id: 'c4-29', nodeId: 'cam-4', label: 'Screaming', timestamp: 63 },
  { id: 'c4-30', nodeId: 'cam-4', label: '"Standby, shots being fired"', timestamp: 64 },
  { id: 'c4-31', nodeId: 'cam-4', label: 'Gunshots', timestamp: 65, isGunfire: true },
  { id: 'c4-32', nodeId: 'cam-4', label: '"Grab the long gun, get in there!"', timestamp: 66 },
  { id: 'c4-33', nodeId: 'cam-4', label: '"Get the long gun!"', timestamp: 68 },
];
